version: '3.8'
services:
  dev-synapse:
    container_name: fabric-synapse-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - DEV=True
    user: vscode
    command: sleep infinity
    healthcheck:
      test: ["CMD", "pgrep", "zsh"]
      interval: 30s
      timeout: 10s
      retries: 3