version: '3.8'
services:
  dev-synapse:
    container_name: fabric-synapse-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCEPT_EULA=Y
    volumes:
      - ..:/workspace:cached
    environment:
      - DEV=True
    user: vscode
    command: sleep infinity
