version: '3.8'

services:
  fabric-remote-tools:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      - AZURE_CLIENT_ID
      - AZURE_TENANT_ID
      - AZURE_CLIENT_SECRET
      - ACCOUNT_NAME
      - WORKSPACE_ID
      - WORKSPACE_NAME
      - LAKEHOUSE_ID
      - LAKEHOUSE_NAME
      - ADO_PERSONAL_ACCESS_TOKEN
      - ADO_ORGANIZATIONAL_URL
      - ADO_PROJECT_NAME
      - ADO_REPO_NAME
      - GH_PERSONAL_ACCESS_TOKEN
      - GH_USERNAME
      - GH_REPO_NAME
    command: /bin/bash -c "python /workspace/set_env_vars.py && bash"