version: '3.8'
services:
  dev-synapse:
    container_name: fabric-synapse-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCEPT_EULA=Y
    ports:
      - "8888:8888"
    volumes:
      - ..:/workspace:cached
      - ~/.azure:/home/vscode/.azure
    environment:
      - DEV=True
    user: vscode
    command: sleep infinity